development:
  cloud_name: best-of-glass
  api_key: '425751676456176'
  api_secret: MEBFvU9HjsxWs4gyn5mNMwJ3eBk
  enhance_image_tag: true
  static_image_support: true
production:
  cloud_name: best-of-glass
  api_key: '425751676456176'
  api_secret: MEBFvU9HjsxWs4gyn5mNMwJ3eBk
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: best-of-glass
  api_key: '425751676456176'
  api_secret: MEBFvU9HjsxWs4gyn5mNMwJ3eBk
  enhance_image_tag: true
  static_image_support: false
